#!/usr/bin/env bash

# nim
# run [n] [prefix] [cores]

n=${1:-}
prefix=${2:-}
cores=${3:-}

cd "$(dirname "$0")"
top=$(git rev-parse --show-toplevel)

# Create build directory
mkdir -p _build

# Only compile if source is newer than binary
if [[ ! -f _build/perms ]] || [[ $(find src -name "*.nim" -newer _build/perms 2>/dev/null | head -1) ]]; then
  nim c -d:release -d:danger --opt:speed --threads:on --hints:off --nimcache:_build/nimcache -o:_build/perms src/perms.nim || exit 1
fi

"$top/bin/log-run" ./_build/perms $n $prefix $cores