#!/usr/bin/env bash

# scala
# run [n] [prefix] [cores]

jvm=true
native=true

n=${1:-}
prefix=${2:-}
cores=${3:-}

cd "$(dirname "$0")"
top=$(git rev-parse --show-toplevel)

if [ "$jvm" ]; then
  scala-cli package --power -f -o perms src/ 2>&1 | grep -v "^Compiling\|^Compiled\|^Wrote\|^Warning\|^Packaging" || exit 1
  "$top/bin/log-run" ./perms $n $prefix $cores
fi

if [ "$native" ]; then
  cd scala-native
  ./run $n $prefix $cores
fi
