#!/usr/bin/env bash

# haskell
# run [n] [prefix] [cores]

n=${1:-8}
prefix=${2:-3}

cores=$(sysctl -n hw.perflevel0.physicalcpu)
cores=${3:-$cores}

cd "$(dirname "$0")"
top=$(git rev-parse --show-toplevel)

cabal build || exit 1

exe=$(cabal list-bin perms 2>/dev/null)
if [[ -z "$exe" ]] || [[ ! -x "$exe" ]]; then
    exe=$(cabal exec -- which perms 2>/dev/null)
fi
if [[ -z "$exe" ]] || [[ ! -x "$exe" ]]; then
    echo "Error: Could not find built executable"
    exit 1
fi

"$top/bin/log-run" "$exe +RTS -N$cores -RTS" $n $prefix $cores